// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceA.proto

package org.foo.bar.svc1;

public interface GreetingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.foo.bar.svc1.Greeting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
