// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceA.proto

package org.foo.bar.svc1;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.foo.bar.svc1.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string first_name = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
