// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceA.proto

package org.foo.bar.svc1;

public final class ServiceAOuterClass {
  private ServiceAOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_foo_bar_svc1_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_foo_bar_svc1_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_foo_bar_svc1_Greeting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_foo_bar_svc1_Greeting_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016serviceA.proto\022\020org.foo.bar.svc1\"/\n\006Pe" +
      "rson\022\022\n\nfirst_name\030\001 \001(\t\022\021\n\tlast_name\030\002 " +
      "\001(\t\"\033\n\010Greeting\022\017\n\007message\030\001 \001(\t2L\n\010Serv" +
      "iceA\022@\n\010sayHello\022\030.org.foo.bar.svc1.Pers" +
      "on\032\032.org.foo.bar.svc1.GreetingB\002P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_foo_bar_svc1_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_foo_bar_svc1_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_foo_bar_svc1_Person_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_org_foo_bar_svc1_Greeting_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_foo_bar_svc1_Greeting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_foo_bar_svc1_Greeting_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
